In [93]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression 
import pickle

In [94]:
df = pd.read_excel("2502.xlsx")
df

     Gender Smoking Alcohol_Consumption Stress_Level   Age   BMI  Heart_Rate
0    Female      No            Moderate         High  90.0  16.6       119.0
1     Other     Yes                 NaN          Low  20.0  29.9        69.0
2      Male     Yes               Heavy          Low  52.0  33.5        54.0
3      Male     Yes               Heavy          Low  15.0  20.3        72.0
4      Male      No            Moderate       Medium  60.0  36.0        58.0
..      ...     ...                 ...          ...   ...   ...         ...
995  Female      No               Heavy       Medium  70.0  21.7        95.0
996  Female      No               Heavy          Low  61.0  29.8        80.0
997  Female      No                 NaN          Low  40.0  33.0        81.0
998    Male     Yes               Heavy         High  94.0  38.5        81.0
999    Male      No            Moderate          Low  33.0  37.0         NaN

[1000 rows x 7 columns]

In [95]:
df.isna().sum()

Gender                  12
Smoking                  7
Alcohol_Consumption    351
Stress_Level             5
Age                      8
BMI                      6
Heart_Rate               8
dtype: int64

In [96]:
df["Gender"].fillna("Unknown", inplace=True)
df["Smoking"].fillna("Unknown", inplace=True)
df["Alcohol_Consumption"].fillna("Unknown", inplace=True)
df.fillna(df.mean(numeric_only=True), inplace=True)

C:\Users\shawo\AppData\Local\Temp\ipykernel_19812\3547146853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna("Unknown", inplace=True)
C:\Users\shawo\AppData\Local\Temp\ipykernel_19812\3547146853.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Smoking"].fillna("Unknown", inplace=True)
C:\Users\shawo\AppData\Local\Temp\ipykernel_19812\3547146853.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Alcohol_Consumption"].fillna("Unknown", inplace=True)

In [97]:
categorical_cols = ["Gender", "Smoking", "Alcohol_Consumption"]
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [105]:
df

     Gender  Smoking  Alcohol_Consumption Stress_Level   Age   BMI  Heart_Rate
0         0        0                    1         High  90.0  16.6  119.000000
1         2        2                    2          Low  20.0  29.9   69.000000
2         1        2                    0          Low  52.0  33.5   54.000000
3         1        2                    0          Low  15.0  20.3   72.000000
4         1        0                    1       Medium  60.0  36.0   58.000000
..      ...      ...                  ...          ...   ...   ...         ...
995       0        0                    0       Medium  70.0  21.7   95.000000
996       0        0                    0          Low  61.0  29.8   80.000000
997       0        0                    2          Low  40.0  33.0   81.000000
998       1        2                    0         High  94.0  38.5   81.000000
999       1        0                    1          Low  33.0  37.0   85.076613

[1000 rows x 7 columns]

In [99]:
for col in categorical_cols:
    le = LabelEncoder() 
    df[col] = le.fit_transform(df[col].astype(str))

In [100]:
x = df.drop("Stress_Level", axis=1)
y = df["Stress_Level"]

In [101]:
print(x.head())

   Gender  Smoking  Alcohol_Consumption   Age   BMI  Heart_Rate
0       0        0                    1  90.0  16.6       119.0
1       2        2                    2  20.0  29.9        69.0
2       1        2                    0  52.0  33.5        54.0
3       1        2                    0  15.0  20.3        72.0
4       1        0                    1  60.0  36.0        58.0

In [102]:
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

In [104]:
scaler = StandardScaler() 
x_scaled = scaler.fit_transform(x)

In [107]:
X_train, X_test, y_train, y_test = train_test_split( x_scaled, y, test_size=0.2, random_state=42 )

In [109]:
model = LinearRegression() 
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [111]:
with open("stress_model.pkl", "wb") as f:
     pickle.dump(model, f)
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f) 
with open("label_encoders.pkl", "wb") as f:
     pickle.dump(label_encoders, f) 
with open("target_encoder.pkl", "wb") as f:
     pickle.dump(target_encoder, f)